character = "crabobot_test"
position = [17689.0, 14964.0, 238.0]
orientation = "East"

[buy_prices]
"common.items.food.cheese" = 50

[sell_prices]
"common.items.armor.boreal.back" = 250_000
"common.items.armor.boreal.belt" = 250_000
"common.items.armor.boreal.chest" = 250_000
"common.items.armor.boreal.foot" = 250_000
"common.items.armor.boreal.hand" = 250_000
"common.items.armor.boreal.pants" = 250_000
"common.items.armor.boreal.shoulder" = 250_000

"common.items.armor.misc.head.boreal_warhelm" = 450_000
"common.items.armor.misc.head.cat_capuche" = 600_000
"common.items.armor.misc.head.hare_hat" = 100_000
"common.items.armor.misc.head.winged_coronet" = 20_000

"common.items.consumable.potion_minor" = 150

"common.items.glider.skullgrin" = 20_000

"common.items.tool.instruments.steeltonguedrum" = 300_000

"common.items.weapons.axe.parashu" = 100_000
"common.items.weapons.sword.caladbolg" = 100_000
"common.items.weapons.staff.laevateinn" = 50_000
"common.items.weapons.hammer.mjolnir" = 100_000
"common.items.weapons.sceptre.caduceus" = 100_000

"common.items.lantern.geode_purple" = 20_000
