position = [17720.0, 14951.0, 237.0]
orientation = 0

[buy_prices]
"food.cheese" = 50
"iron|sword.greatsword|sword.long" = 1_000

[sell_prices]
"consumable.potion_minor" = 150
"iron|sword.greatsword|sword.long" = 1_000
