position = [17720.0, 14951.0, 237.0]
orientation = 0

[buy_prices.simple]
"food.cheese" = 50

[[buy_prices.modular]]
material = "Iron"
primary = "sword.greatsword"
secondary = "sword.long"
price = 1000

[sell_prices.simple]
"consumable.potion_minor" = 150

[[sell_prices.modular]]
material = "Iron"
primary = "sword.greatsword"
secondary = "sword.long"
price = 1000
